/**:
  ros__parameters:
    port: "/dev/ttyACM0"
    brake_max: 15.0
    brake_min: -15.0
    current_max: 15.0
    current_min: 0.0
    duty_cycle_max: 0.5
    duty_cycle_min: 0.0
    position_max: 0.5
    position_min: 0.0
    servo_max: 180.0
    servo_min: -180.0
    speed_max: 4000.0
    speed_min: -5000.0
